

try{
    throw new EvalError('Se ha producido un error en la l√≠nea 100');
}catch(error){
    console.error('hay un error');
}